language: python
matrix:
  include:
    - python: 3.6
      env: FLASK=1.0.2 PYLINT=2.3 PYMYSQL=0.9.3 PYTEST=4.3
os: linux

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-3.7.0-Linux-x86_64.sh -O ~/miniconda.sh
  - bash ~/miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda

  # Useful for debugging any issues with conda
  - conda info -a

install:
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION flask=$FLASK pylint=$PYLINT pymysql=$PYMYSQL pytest=$PYTEST
  - source activate test-environment
  - python setup.py install

script:
  - py.test
  - pylint
