name: IO2019
channels:
  - defaults
dependencies:
  - asn1crypto=0.24.0
  - astroid=2.2.5
  - atomicwrites=1.3.0
  - attrs=19.1.0
  - ca-certificates=2019.1.23
  - certifi=2019.3.9
  - cffi=1.12.2
  - click=7.0
  - cryptography=2.6.1
  - flask=1.0.2
  - idna=2.8
  - isort=4.3.16
  - itsdangerous=1.1.0
  - jinja2=2.10
  - lazy-object-proxy=1.3.1
  - libcxx=4.0.1
  - libcxxabi=4.0.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - markupsafe=1.1.1
  - mccabe=0.6.1
  - more-itertools=6.0.0
  - ncurses=6.1
  - openssl=1.1.1b
  - pip=19.0.3
  - pluggy=0.9.0
  - py=1.8.0
  - pycparser=2.19
  - pylint=2.3.1
  - pymysql=0.9.3
  - pytest=4.3.1
  - python=3.6.8
  - readline=7.0
  - setuptools=40.8.0
  - six=1.12.0
  - sqlite=3.27.2
  - tk=8.6.8
  - typed-ast=1.3.1
  - werkzeug=0.14.1
  - wheel=0.33.1
  - wrapt=1.11.1
  - xz=5.2.4
  - zlib=1.2.11

