name: IO2019-server
channels:
  - defaults
  - conda-forge
dependencies:
  - flask=1.0.2
  - jinja2>=2.10
  - pylint>=2.3.1
  - pytest>=4.3.1
  - python=3.6.8
  - black>=19.3b0
  - sqlite>=3.27
  - flask-sqlalchemy>=2.3.1
  - flask-cors>=3.0
  - sqlalchemy>=1.3
  - flask-login
  - pyjwt
  - gunicorn # for app deployment